export const invalidAds = [{}, { Id: 'adsf' }]

export const validAds = [
  {
    IsActive: true,
    DontAffectParentFreqCap: false,
    Creative: {
      IsActive: true,
      ImageName: '',
      SaveEmptyCreative: null,
      Body: '',
      IsNetworkAd: null,
      Alt: null,
      Title: 'Adzerk Creative',
      IsDeleted: false,
      IsSync: null,
      Url: 'http://adzerk.com',
      IsIdOnly: false,
      IsNoTrack: null,
      TemplateValues: null,
      TemplateId: null,
      ImageLink: 'http://s.zkcdn.net/Advertisers/',
      ScriptBody: '',
      AdvertiserId: 123,
      Metadata: null,
      AdTypeId: 5,
      IsHTMLJS: false,
      Id: 12345,
    },
    FreqCapType: null,
    EndDate: null,
    Iframe: null,
    ZoneId: null,
    PublisherAccountId: 0,
    IsDeleted: false,
    CustomTargeting: '$keywords contains "dean"',
    EndDateISO: '2017-12-05T12:00:00.000Z',
    RtbCustomFields: null,
    Impressions: 100,
    GoalType: 1,
    Goal: 200000,
    Price: 1,
    FreqCapDuration: null,
    Percentage: 0,
    FreqCap: null,
    IsStartEndDateOverride: true,
    CustomRelevancyScore: null,
    FlightId: 7290072,
    ActiveKeywords: ['kittens', 'cats'],
    SiteId: null,
    CampaignId: 123,
    Id: 12345,
    IsGoalOverride: true,
    StartDateISO: '2017-05-01T12:00:00.000Z',
  },
]
