import {
  CapTypeEnum,
  DeliveryStatusEnum,
  DuplicateModeEnum,
  FrequencyCapTypeEnum,
  GoalTypeEnum,
  RateTypeEnum,
} from './base/enums'
import { AdSchema } from './Ad'
import { BehavioralTargetSchema } from './BehavioralTarget'
import { DateSchema } from './base/Date'
import { GeoTargetSchema } from './GeoTarget'
import { SiteZoneSchema } from './SiteZone'
import { z } from 'zod'

export const FlightSchema = z.object({
  BehavioralTargeting: BehavioralTargetSchema.optional().nullable(),
  CampaignId: z.number(),
  CanPassback: z.boolean().optional().nullable(),
  CapType: CapTypeEnum.optional().nullable(),
  CeilingECPM: z.number().optional().nullable(),
  Created: DateSchema.optional().nullable(),
  CreativeMaps: z.array(AdSchema).optional().nullable(),
  CustomFieldsJson: z.string().optional().nullable(),
  CustomTargeting: z.string().optional().nullable(),
  DailyCapAmount: z.number().optional().nullable(),
  DailyCapAmountDecimal: z.number().optional().nullable(),
  DatePartingEndTime: DateSchema.optional().nullable(),
  DatePartingEndTimeISO: DateSchema.optional().nullable(),
  DatePartingStartTime: DateSchema.optional().nullable(),
  DatePartingStartTimeISO: DateSchema.optional().nullable(),
  DefaultECPM: z.number().optional().nullable(),
  DeliveryStatus: DeliveryStatusEnum.optional().nullable(),
  DontAffectParentFreqCap: z.boolean().optional().nullable(),
  DuplicateMode: DuplicateModeEnum.optional().nullable(),
  ECPMBurnInImpressions: z.number().optional().nullable(),
  ECPMMultiplier: z.number().optional().nullable(),
  ECPMOptimizePeriod: z.number().optional().nullable(),
  EffectiveCPMOverride: z.number().optional().nullable(),
  EndDate: z.string().optional().nullable(),
  EndDateISO: DateSchema.optional().nullable(),
  FloorECPM: z.number().optional().nullable(),
  FreqCap: z.number().optional().nullable(),
  FreqCapDuration: z.number().optional().nullable(),
  FreqCapType: FrequencyCapTypeEnum.optional().nullable(),
  GeoTargeting: z.array(GeoTargetSchema).optional().nullable(),
  GoalType: GoalTypeEnum,
  Id: z.number().optional(),
  Impressions: z.number(),
  IsActive: z.boolean().default(false),
  IsArchived: z.boolean().optional().nullable(),
  IsCompanion: z.boolean().optional().nullable(),
  IsDeleted: z.boolean().optional(),
  IsECPMOptimized: z.boolean().optional().nullable(),
  IsFreqCap: z.boolean().optional().nullable(),
  IsFriday: z.boolean().optional().nullable(),
  IsFullSpeed: z.boolean().optional().nullable(),
  IsMonday: z.boolean().optional().nullable(),
  IsNoDuplicates: z.boolean().optional().nullable(),
  IsSaturday: z.boolean().optional().nullable(),
  IsSunday: z.boolean().optional().nullable(),
  IsTargetingOptimization: z.boolean().optional().nullable(),
  IsThursday: z.boolean().optional().nullable(),
  IsTrackingConversions: z.boolean().optional().nullable(),
  IsTuesday: z.boolean().optional().nullable(),
  IsUnlimited: z.boolean().optional().nullable(),
  IsWednesday: z.boolean().optional().nullable(),
  Keywords: z.string().optional().nullable(),
  LastModified: DateSchema.optional().nullable(),
  LifetimeCapAmount: z.number().optional().nullable(),
  LifetimeCapAmountDecimal: z.number().optional().nullable(),
  Name: z.string(),
  NoEndDate: z.boolean().optional().nullable(),
  OptionType: z.number().optional().nullable(),
  PassbackSortOrder: z.number().optional().nullable(),
  Price: z.number().optional().nullable(),
  PriorityId: z.number(),
  RateType: RateTypeEnum.optional().nullable(),
  RequireStrictLocation: z.boolean().optional().nullable(),
  SiteZoneTargeting: z.array(SiteZoneSchema).optional().nullable(),
  StartDate: z.string().optional().nullable(),
  StartDateISO: DateSchema.optional().nullable(),
  TargetingOptimizationBurnIn: z.number().optional().nullable(),
  TargetingOptimizationCanMiss: z.boolean().optional().nullable(),
  TargetingOptimizationTarget: z.number().optional().nullable(),
  TargetingOptimizationTargetType: z.number().optional().nullable(),
  TargetingOptimizationType: z.number().optional().nullable(),
  TargetROAS: z.number().optional().nullable(),
  TimeZone: z.string().optional(),
  Version: z.number().optional().nullable(),

  // TODO: Determine type
  AttributionClick: z.any().optional().nullable(),
  AttributionView: z.any().optional().nullable(),
  CustomRelevancyScore: z.any().optional().nullable(),
  GeoDistanceTargeting: z.array(z.any()).optional().nullable(),
  UserAgentKeywords: z.any().optional().nullable(),
  WeightOverride: z.any().optional().nullable(),
})

export type FlightSchema = z.infer<typeof FlightSchema>

// * ROAS: Return on ad spend
// * ECPM: “effective cost per thousand impressions” or “effective cost per mille”
